// Generated by CoffeeScript 1.8.0
(function() {
  var tanaApp;

  tanaApp = angular.module('tanaApp', ['ngResource', 'ngCookies']);

  tanaApp.config(function ($httpProvider) {
    $httpProvider.defaults.withCredentials = true;
  });

  tanaApp.controller('MainCtrl', function($scope, $resource, $http, $cookies) {
    var bookmark, headers;
    console.dir($cookies);
    $http.defaults.useXDomain = true;
    bookmark = $resource("http://b.hatena.ne.jp/bokuweb/search/json", {}, {
      method: "GET",
      withCredentials: true
    });
    return $scope.bookmark = bookmark.query();
  });

}).call(this);
